-- DROP DATABASE IF EXISTS customer_service_db;
-- CREATE DATABASE customer_service_db;
-- \c customer_service_db;

-- Drop tables (in dependency order)
DROP TABLE IF EXISTS user_companies;
DROP TABLE IF EXISTS companies;
DROP TYPE IF EXISTS user_role;

-- User role enum
CREATE TYPE user_role AS ENUM ('user', 'manager', 'admin');

-- Companies table
CREATE TABLE companies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    address VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- User companies table
CREATE TABLE user_companies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    id_auth_kc VARCHAR(255) NOT NULL UNIQUE,
    role user_role NOT NULL DEFAULT 'user',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
